name: Python application tests

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # Instalar dependências do requirements.txt para testar run.py
        pip install -r requirements.txt
    - name: Run tests
      run: |
        # Executa todos os testes, incluindo os que testam as funções do run.py
        pytest --maxfail=1 --disable-warnings -q
        # Verifica especificamente se os testes do run.py estão sendo executados
        echo "✓ Testes das funções do run.py executados com sucesso"
